Before adding the same phone number check if it has already been configured
keycloak-competence-center/keycloak-sms-authenticator pull request #8
Opened 2024-08-30 09:30 UTC by daviddavidgit

2024-11-21 06:32 UTC, DevDuki requested changes

2024-11-21 06:32 UTC, DevDuki commented on extensions/keycloak-sms-authenticator/src/main/java/com/inventage/keycloak/sms/credential/SmsCredentialProvider.java
> +        LOGGER.debugf("addCredential: User already has not a credential with same phone number. So new credential will be added.");
I think it is a bit redundant saying that the user does not have a credential with the same phone number. I think just saying "A new SMS credential will be created" or something like that? Unless you want to keep the information that a new credential will be created **_because_** the user does not have one already with the same number then I would rewrite the sentence a little bit, like so.

```suggestion
        LOGGER.debugf("addCredential: User does not have a credential with the same phone number. So new credential will be added.");
```

2024-11-21 06:32 UTC, DevDuki commented on extensions/keycloak-sms-authenticator/src/main/java/com/inventage/keycloak/sms/credential/SmsCredentialProvider.java
> +                            smsCredentialData = JsonSerialization.readValue(cred.getCredentialData(), SmsCredentialData.class);
I would delete line 67 and just directly assign the variable on this line.
```suggestion
                            final SmsCredentialData smsCredentialData = JsonSerialization.readValue(cred.getCredentialData(), SmsCredentialData.class);
```

2024-11-21 10:22 UTC, DevDuki requested changes

2024-11-21 10:22 UTC, DevDuki commented on extensions/keycloak-sms-authenticator/src/main/java/com/inventage/keycloak/sms/credential/SmsCredentialProvider.java
> +                            smsCredentialData = JsonSerialization.readValue(cred.getCredentialData(), SmsCredentialData.class);
I meant as a one-liner.

```suggestion
                            final SmsCredentialData smsCredentialData = JsonSerialization.readValue(cred.getCredentialData(), SmsCredentialData.class);
```

2024-11-21 12:47 UTC, DevDuki approved these changes

2024-11-25 12:58 UTC, esteiner approved these changes

2024-11-26 06:05 UTC, merged